FROM python:3.8

LABEL author="Andy"
LABEL description="Dockerfile for send.py"

COPY send.py /code/
COPY inputvagapython.csv /code/
COPY requirements.txt /code/

WORKDIR /code/

RUN pip install -r requirements.txt

CMD ['python3', 'send.py']